
langchain4j:
  open-ai:
#    chat-model:
    streaming-chat-model:
       #流式模型配置
      base-url: http://localhost:11434/v1
      api-key: "N/A"
#      model-name: qwen3:8b
      model-name: qwen3:14b-q4_K_M #负担太大
      log-requests: true
      log-responses: true
#      system-message: "你是一个AI助手。请不要在回答中显示思考过程，直接提供最终答案。不要使用<think>标签或显示内部推理过程。"
    embedding-model:
      #流式模型配置
      base-url: http://localhost:11434/v1
      api-key: "N/A"
      model-name: qwen3-embedding-4B-Q6_K
      log-requests: true
      log-responses: true
#      system-message: "你是一个AI助手。请不要在回答中显示思考过程，直接提供最终答案。不要使用<think>标签或显示内部推理过程。"
  community:
    redis:
      host: localhost
      port: 6379
  web-search-engine:
    tavily:
      api-key: "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"
#logging:
#  level:
#    dev.langchain4j: debug

spring:
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/volunteer?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234

mybatis:
  configuration:
    map-underscore-to-camel-case: true
rag:
  ingestion:
    enabled: false

